# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
    imports =
        [ (modulesPath + "/installer/scan/not-detected.nix")
        ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-intel" "kvmfr" "vfio_virqfd" "vfio_pci" "vfio_iommu_type1" "vfio" ];
    boot.kernelParams = [ "intel_iommu=on" "intel_iommu=pt" "kvm.ignore_msrs=1" ];
    # boot.extraModulePackages = [ config.boot.kernelPackages.kvmfr ];
    boot.extraModprobeConfig = ''
        options kvmfr static_size_mb=32
    '';

    services.udev.extraRules = ''
    SUBSYSTEM=="kvmfr", OWNER="user", GROUP="kvm", MODE="0660"
    '';

    fileSystems."/" =
        { device = "/dev/disk/by-uuid/89e1715d-6cb7-4719-b897-147a05c7fb5a";
            fsType = "ext4";
        };

    fileSystems."/bin" =
        { device = "/usr/bin";
            fsType = "none";
            options = [ "bind" ];
        };

    fileSystems."/boot" =
        { device = "/dev/disk/by-uuid/DDCD-59AD";
            fsType = "vfat";
            options = [ "fmask=0077" "dmask=0077" ];
        };

    swapDevices =
        [ { device = "/dev/disk/by-uuid/7a1f9958-913e-44b4-a3d0-cac1f92f6212"; }
        ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
