#!/usr/bin/env bash

pkill eww
pkill swww
eww daemon

eww open bar
eww open desktop
eww open notifications_popup

swww init
swww img ~/.wallpapers/wallhaven.png

# $HOME/.config/eww/scripts/myshell/myshell --eww --file
