#!/usr/bin/env bash

function state {
  STATE=$(bluetoothctl show | grep 'Powered' | awk '{print $2}')
  if [[ $STATE == 'yes' ]]; then echo 'on'
  else echo 'off'; fi
}

function toggle {
  if [[ $(state) = 'on' ]]; then bluetoothctl power off
  else bluetoothctl power on; fi
}

function connected {
    echo `bluetoothctl devices Connected |  cut -d' ' -f3-`
}

function icon() {
    if [[ $(state) = 'on' ]]; then echo ''
    # elif [[ $PERCENT -ge 1  ]]; then echo ' '
    else echo ''
    fi
}

FRAME=$(date +%s%3N)
FRAMETOTAL=245

function get {
    echo "{
    \"connected\": \"$(connected)\", 
    \"state\": \"$(state)\", 
    \"icon\": \"$(icon)\", 
    \"frame\": \"$((FRAME / 60 % FRAMETOTAL))\"
}"
}

if [[ $1 == 'toggle' ]]; then toggle; fi
if [[ $1 == 'get' ]]; then get; fi
