import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]

# # [colors.bright]
# # black = "0x181818"
# # blue = "0x00B4FF"
# # cyan = "0x89ddff"
# # green = "0x00C44D"
# # magenta = "0xfae4fc"
# # red = "0xFF449E"
# # white = "0xEEEEEE"
# # yellow = "0x00C0BA"
#
# [colors.cursor]
# cursor = "CellForeground"
# text = "CellBackground"
#
# # [colors.normal]
# # black = "0x1b1e28"
# # blue = "#435c89"
# # cyan = "0xadd7ff"
# # green = "0x5de4c7"
# # magenta = "0xfcc5e9"
# # red = "0xd0679d"
# # white = "0xffffff"
# # yellow = "0xfffac2"
#
# [colors.primary]
# background = "0x181818"
# foreground = "0xa6accd"
#
# [colors.search.focused_match]
# background = "0xadd7ff"
# foreground = "0x1b1e28"
#
# [colors.search.matches]
# background = "0xadd7ff"
# foreground = "0x1b1e28"
#
# [colors.selection]
# background = "0x303340"
# text = "CellForeground"
#
# [colors.vi_mode_cursor]
# cursor = "CellForeground"
# text = "CellBackground"
#
# [cursor]
# style = "Underline"
# vi_mode_style = "Underline"
#
# [env]
# TERM = "xterm-256color"
#
[font]
size = 12.0
#
[font.bold]
family = "Hurmit Nerd Font"
style = "Bold"
#
# [font.glyph_offset]
# y = 0
#
[font.italic]
family = "Hurmit Nerd Font"
style = "Italic"
#
[font.normal]
family = "Hurmit Nerd Font"
style = "Regular"
#
# [font.offset]
# y = 0
#
# [scrolling]
# history = 1000
# multiplier = 3
#
# [window]
# decorations = "none"
# opacity = 0.7
#
# [window.dimensions]
# columns = 80
# lines = 35
#
[window.padding]
x = 16
y = 16
